name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/unity-editmode.yml
    secrets: inherit
