name: Unity EditMode

on:
  workflow_call:

env:
  UNITY_VERSION: 6000.5.9f1

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false

      - uses: actions/cache@v5
        with:
          path: Library
          key: Library-test-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-test-

      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          customImage: unityci/editor:ubuntu-6000.5.9f1-base-3
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: Test-results
          path: artifacts
